name: Compile Slides

on:
    push:
        branches:
            - master

jobs:
    Compile-Slides:
        runs-on: ubuntu-latest
        steps:
            - name: Updating apt
              run: sudo apt-get update
            - name: Installing pandoc
              run: sudo apt-get install pandoc -y
            - name: Installing pdflatex
              run: sudo apt install texlive-latex-extra -y
            - uses: actions/checkout@v5
            - name: Compiling Slides
              run: |
                bash compile.bash
            - name: Commit slides.pdf
              run: |
                git config --local user.email "github-actions[bot]@users.noreply.github.com"
                git config --local user.name "github-actions[bot]"
                git add -f slides.pdf
                git commit -m "[chore] Compiled and saved slides" || echo "no changes"
            - name: Push Commit
              run: git push